name: SamplePlugin
author: DarkBow_
version: 1.0
main: fr.darkbow_.sampleplugin.SamplePlugin
api-version: 1.16
commands:
  generatewaypoints:
    description: Génère des waypoints et les orientations pour cibler le point (0, 10, 0) avec un cercle de rayon 10.
  tstart:
    description: Start the timelapse teleportation sequence.
  tstop:
    description: Stop the timelapse teleportation sequence.